var searchData=
[
  ['datadepth',['DataDepth',['../d7/d0e/classcv_1_1DataDepth.html',1,'cv']]],
  ['datatype',['Datatype',['../d4/dbd/structcvflann_1_1Datatype.html',1,'cvflann']]],
  ['datatype',['DataType',['../d0/d3a/classcv_1_1DataType.html',1,'cv']]],
  ['datatype_3c_20char_20_3e',['Datatype&lt; char &gt;',['../d3/df4/structcvflann_1_1Datatype_3_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20double_20_3e',['Datatype&lt; double &gt;',['../d2/d8d/structcvflann_1_1Datatype_3_01double_01_4.html',1,'cvflann']]],
  ['datatype_3c_20float_20_3e',['Datatype&lt; float &gt;',['../dd/d42/structcvflann_1_1Datatype_3_01float_01_4.html',1,'cvflann']]],
  ['datatype_3c_20short_20_3e',['Datatype&lt; short &gt;',['../db/de5/structcvflann_1_1Datatype_3_01short_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20char_20_3e',['Datatype&lt; unsigned char &gt;',['../d3/dea/structcvflann_1_1Datatype_3_01unsigned_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20short_20_3e',['Datatype&lt; unsigned short &gt;',['../dc/dbe/structcvflann_1_1Datatype_3_01unsigned_01short_01_4.html',1,'cvflann']]],
  ['deblurerbase',['DeblurerBase',['../dd/d05/classcv_1_1videostab_1_1DeblurerBase.html',1,'cv::videostab']]],
  ['defaultcopypolicy',['DefaultCopyPolicy',['../d8/dc2/structcv_1_1cudev_1_1DefaultCopyPolicy.html',1,'cv::cudev']]],
  ['defaultglobreducepolicy',['DefaultGlobReducePolicy',['../d2/d04/structcv_1_1cudev_1_1DefaultGlobReducePolicy.html',1,'cv::cudev']]],
  ['defaulthistogrampolicy',['DefaultHistogramPolicy',['../d4/d2b/structcv_1_1cudev_1_1DefaultHistogramPolicy.html',1,'cv::cudev']]],
  ['defaultreducetovecpolicy',['DefaultReduceToVecPolicy',['../d3/dd7/structcv_1_1cudev_1_1DefaultReduceToVecPolicy.html',1,'cv::cudev']]],
  ['defaultsplitmergepolicy',['DefaultSplitMergePolicy',['../d9/d3a/structcv_1_1cudev_1_1DefaultSplitMergePolicy.html',1,'cv::cudev']]],
  ['defaulttransformpolicy',['DefaultTransformPolicy',['../db/db3/structcv_1_1cudev_1_1DefaultTransformPolicy.html',1,'cv::cudev']]],
  ['defaulttransposepolicy',['DefaultTransposePolicy',['../dd/d44/structcv_1_1cudev_1_1DefaultTransposePolicy.html',1,'cv::cudev']]],
  ['denseopticalflow',['DenseOpticalFlow',['../d6/d4a/classcv_1_1cuda_1_1DenseOpticalFlow.html',1,'cv::cuda']]],
  ['denseopticalflow',['DenseOpticalFlow',['../df/dde/classcv_1_1DenseOpticalFlow.html',1,'cv']]],
  ['denseopticalflowext',['DenseOpticalFlowExt',['../d1/d21/classcv_1_1superres_1_1DenseOpticalFlowExt.html',1,'cv::superres']]],
  ['densepyrlkopticalflow',['DensePyrLKOpticalFlow',['../d0/da4/classcv_1_1cuda_1_1DensePyrLKOpticalFlow.html',1,'cv::cuda']]],
  ['derivxptr',['DerivXPtr',['../df/d8b/structcv_1_1cudev_1_1DerivXPtr.html',1,'cv::cudev']]],
  ['derivxptrsz',['DerivXPtrSz',['../db/d58/structcv_1_1cudev_1_1DerivXPtrSz.html',1,'cv::cudev']]],
  ['derivyptr',['DerivYPtr',['../dc/d51/structcv_1_1cudev_1_1DerivYPtr.html',1,'cv::cudev']]],
  ['derivyptrsz',['DerivYPtrSz',['../d2/dfc/structcv_1_1cudev_1_1DerivYPtrSz.html',1,'cv::cudev']]],
  ['descriptorcollection',['DescriptorCollection',['../d4/dac/classcv_1_1DescriptorMatcher_1_1DescriptorCollection.html',1,'cv::DescriptorMatcher']]],
  ['descriptormatcher',['DescriptorMatcher',['../dd/dc5/classcv_1_1cuda_1_1DescriptorMatcher.html',1,'cv::cuda']]],
  ['descriptormatcher',['DescriptorMatcher',['../db/d39/classcv_1_1DescriptorMatcher.html',1,'cv']]],
  ['detectionroi',['DetectionROI',['../d3/d34/structcv_1_1DetectionROI.html',1,'cv']]],
  ['device',['Device',['../d7/d9f/classcv_1_1ocl_1_1Device.html',1,'cv::ocl']]],
  ['deviceinfo',['DeviceInfo',['../d7/d7c/classcv_1_1cuda_1_1DeviceInfo.html',1,'cv::cuda']]],
  ['direction_5ffunc',['direction_func',['../d3/d97/structcv_1_1cudev_1_1direction__func.html',1,'cv::cudev']]],
  ['disableif',['DisableIf',['../df/d27/structcv_1_1cudev_1_1DisableIf.html',1,'cv::cudev']]],
  ['disableif_3c_20false_2c_20t_20_3e',['DisableIf&lt; false, T &gt;',['../d5/d19/structcv_1_1cudev_1_1DisableIf_3_01false_00_01T_01_4.html',1,'cv::cudev']]],
  ['disjointsets',['DisjointSets',['../dc/d3e/classcv_1_1detail_1_1DisjointSets.html',1,'cv::detail']]],
  ['disparitybilateralfilter',['DisparityBilateralFilter',['../d8/d4f/classcv_1_1cuda_1_1DisparityBilateralFilter.html',1,'cv::cuda']]],
  ['distindex',['DistIndex',['../d0/d28/structcvflann_1_1UniqueResultSet_1_1DistIndex.html',1,'cvflann::UniqueResultSet']]],
  ['divides',['divides',['../de/d2a/structcv_1_1cudev_1_1divides.html',1,'cv::cudev']]],
  ['dmatch',['DMatch',['../d4/de0/classcv_1_1DMatch.html',1,'cv']]],
  ['downhillsolver',['DownhillSolver',['../d4/d43/classcv_1_1DownhillSolver.html',1,'cv']]],
  ['dpseamfinder',['DpSeamFinder',['../d0/dd5/classcv_1_1detail_1_1DpSeamFinder.html',1,'cv::detail']]],
  ['drawmatchesflags',['DrawMatchesFlags',['../de/d30/structcv_1_1DrawMatchesFlags.html',1,'cv']]],
  ['dtrees',['DTrees',['../d8/d89/classcv_1_1ml_1_1DTrees.html',1,'cv::ml']]],
  ['dualtvl1opticalflow',['DualTVL1OpticalFlow',['../dc/d47/classcv_1_1DualTVL1OpticalFlow.html',1,'cv']]],
  ['dualtvl1opticalflow',['DualTVL1OpticalFlow',['../d6/db1/classcv_1_1superres_1_1DualTVL1OpticalFlow.html',1,'cv::superres']]],
  ['dynamicbitset',['DynamicBitset',['../d1/d73/classcvflann_1_1DynamicBitset.html',1,'cvflann']]],
  ['dynamicsharedmem',['DynamicSharedMem',['../d3/d2b/structcv_1_1cudev_1_1DynamicSharedMem.html',1,'cv::cudev']]],
  ['dynamicsharedmem_3c_20double_20_3e',['DynamicSharedMem&lt; double &gt;',['../db/d28/structcv_1_1cudev_1_1DynamicSharedMem_3_01double_01_4.html',1,'cv::cudev']]]
];
