var searchData=
[
  ['calibratecrf',['CalibrateCRF',['../dd/de3/classcv_1_1CalibrateCRF.html',1,'cv']]],
  ['calibratedebevec',['CalibrateDebevec',['../da/d27/classcv_1_1CalibrateDebevec.html',1,'cv']]],
  ['calibraterobertson',['CalibrateRobertson',['../d3/d30/classcv_1_1CalibrateRobertson.html',1,'cv']]],
  ['camera',['Camera',['../dc/d3a/classcv_1_1viz_1_1Camera.html',1,'cv::viz']]],
  ['cameraparams',['CameraParams',['../d4/d0a/structcv_1_1detail_1_1CameraParams.html',1,'cv::detail']]],
  ['cannyedgedetector',['CannyEdgeDetector',['../d0/d43/classcv_1_1cuda_1_1CannyEdgeDetector.html',1,'cv::cuda']]],
  ['cascadeclassifier',['CascadeClassifier',['../d1/de5/classcv_1_1CascadeClassifier.html',1,'cv']]],
  ['cascadeclassifier',['CascadeClassifier',['../d9/d80/classcv_1_1cuda_1_1CascadeClassifier.html',1,'cv::cuda']]],
  ['chihistogramcostextractor',['ChiHistogramCostExtractor',['../dd/d43/classcv_1_1ChiHistogramCostExtractor.html',1,'cv']]],
  ['chisquaredistance',['ChiSquareDistance',['../dd/dd8/structcvflann_1_1ChiSquareDistance.html',1,'cvflann']]],
  ['choose_5fpolicy',['choose_policy',['../d5/da1/structcvflann_1_1anyimpl_1_1choose__policy.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20any_20_3e',['choose_policy&lt; any &gt;',['../d5/d51/structcvflann_1_1anyimpl_1_1choose__policy_3_01any_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20bool_20_3e',['choose_policy&lt; bool &gt;',['../d9/d10/structcvflann_1_1anyimpl_1_1choose__policy_3_01bool_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20float_20_3e',['choose_policy&lt; float &gt;',['../d2/d87/structcvflann_1_1anyimpl_1_1choose__policy_3_01float_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20char_20_3e',['choose_policy&lt; signed char &gt;',['../dc/d84/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01char_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20long_20_3e',['choose_policy&lt; signed long &gt;',['../d7/d22/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01long_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20short_20_3e',['choose_policy&lt; signed short &gt;',['../d3/d4a/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01short_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20t_20_2a_20_3e',['choose_policy&lt; T * &gt;',['../d0/db0/structcvflann_1_1anyimpl_1_1choose__policy_3_01T_01_5_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20char_20_3e',['choose_policy&lt; unsigned char &gt;',['../dd/dd1/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01char_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20long_20_3e',['choose_policy&lt; unsigned long &gt;',['../d9/dcd/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01long_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20short_20_3e',['choose_policy&lt; unsigned short &gt;',['../d9/dd6/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01short_01_4.html',1,'cvflann::anyimpl']]],
  ['clahe',['CLAHE',['../d6/db6/classcv_1_1CLAHE.html',1,'cv']]],
  ['clahe',['CLAHE',['../db/d79/classcv_1_1cuda_1_1CLAHE.html',1,'cv::cuda']]],
  ['color',['Color',['../d4/dba/classcv_1_1viz_1_1Color.html',1,'cv::viz']]],
  ['coloraverageinpainter',['ColorAverageInpainter',['../d1/dc6/classcv_1_1videostab_1_1ColorAverageInpainter.html',1,'cv::videostab']]],
  ['colorinpainter',['ColorInpainter',['../d3/d2b/classcv_1_1videostab_1_1ColorInpainter.html',1,'cv::videostab']]],
  ['commandlineparser',['CommandLineParser',['../d0/d2e/classcv_1_1CommandLineParser.html',1,'cv']]],
  ['commonareainterptr',['CommonAreaInterPtr',['../d8/d3d/structcv_1_1cudev_1_1CommonAreaInterPtr.html',1,'cv::cudev']]],
  ['commonareainterptrsz',['CommonAreaInterPtrSz',['../db/d1c/structcv_1_1cudev_1_1CommonAreaInterPtrSz.html',1,'cv::cudev']]],
  ['comparet',['CompareT',['../d2/d76/structcvflann_1_1Heap_1_1CompareT.html',1,'cvflann::Heap']]],
  ['complex',['Complex',['../da/df6/classcv_1_1Complex.html',1,'cv']]],
  ['compositeindex',['CompositeIndex',['../dc/d59/classcvflann_1_1CompositeIndex.html',1,'cvflann']]],
  ['compositeindexparams',['CompositeIndexParams',['../d5/d94/structcv_1_1flann_1_1CompositeIndexParams.html',1,'cv::flann']]],
  ['compositeindexparams',['CompositeIndexParams',['../db/d3f/structcvflann_1_1CompositeIndexParams.html',1,'cvflann']]],
  ['compressedrectilinearportraitprojector',['CompressedRectilinearPortraitProjector',['../d0/ded/structcv_1_1detail_1_1CompressedRectilinearPortraitProjector.html',1,'cv::detail']]],
  ['compressedrectilinearportraitwarper',['CompressedRectilinearPortraitWarper',['../dd/dc8/classcv_1_1detail_1_1CompressedRectilinearPortraitWarper.html',1,'cv::detail']]],
  ['compressedrectilinearportraitwarper',['CompressedRectilinearPortraitWarper',['../de/d9a/classcv_1_1CompressedRectilinearPortraitWarper.html',1,'cv']]],
  ['compressedrectilinearprojector',['CompressedRectilinearProjector',['../db/dbb/structcv_1_1detail_1_1CompressedRectilinearProjector.html',1,'cv::detail']]],
  ['compressedrectilinearwarper',['CompressedRectilinearWarper',['../dd/dbe/classcv_1_1detail_1_1CompressedRectilinearWarper.html',1,'cv::detail']]],
  ['compressedrectilinearwarper',['CompressedRectilinearWarper',['../d0/dd5/classcv_1_1CompressedRectilinearWarper.html',1,'cv']]],
  ['conjgradsolver',['ConjGradSolver',['../d0/d21/classcv_1_1ConjGradSolver.html',1,'cv']]],
  ['consistentmosaicinpainter',['ConsistentMosaicInpainter',['../d9/dba/classcv_1_1videostab_1_1ConsistentMosaicInpainter.html',1,'cv::videostab']]],
  ['constantptr',['ConstantPtr',['../d5/db7/structcv_1_1cudev_1_1ConstantPtr.html',1,'cv::cudev']]],
  ['constantptrsz',['ConstantPtrSz',['../d2/df7/structcv_1_1cudev_1_1ConstantPtrSz.html',1,'cv::cudev']]],
  ['context',['Context',['../d1/d45/classcv_1_1ocl_1_1Context.html',1,'cv::ocl']]],
  ['converttuple',['ConvertTuple',['../d9/d6a/structcv_1_1cudev_1_1ConvertTuple.html',1,'cv::cudev']]],
  ['convolution',['Convolution',['../d4/d25/classcv_1_1cuda_1_1Convolution.html',1,'cv::cuda']]],
  ['cornernesscriteria',['CornernessCriteria',['../dd/d63/classcv_1_1cuda_1_1CornernessCriteria.html',1,'cv::cuda']]],
  ['cornersdetector',['CornersDetector',['../de/d95/classcv_1_1cuda_1_1CornersDetector.html',1,'cv::cuda']]],
  ['cos_5ffunc',['cos_func',['../d6/dfb/structcv_1_1cudev_1_1cos__func.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20double_20_3e',['cos_func&lt; double &gt;',['../db/d23/structcv_1_1cudev_1_1cos__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20float_20_3e',['cos_func&lt; float &gt;',['../dd/d7a/structcv_1_1cudev_1_1cos__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20schar_20_3e',['cos_func&lt; schar &gt;',['../dc/d25/structcv_1_1cudev_1_1cos__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20short_20_3e',['cos_func&lt; short &gt;',['../d7/d03/structcv_1_1cudev_1_1cos__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20uchar_20_3e',['cos_func&lt; uchar &gt;',['../dd/d3d/structcv_1_1cudev_1_1cos__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20uint_20_3e',['cos_func&lt; uint &gt;',['../da/dc1/structcv_1_1cudev_1_1cos__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20ushort_20_3e',['cos_func&lt; ushort &gt;',['../df/d35/structcv_1_1cudev_1_1cos__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc',['cosh_func',['../dc/d8a/structcv_1_1cudev_1_1cosh__func.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20double_20_3e',['cosh_func&lt; double &gt;',['../d5/d3a/structcv_1_1cudev_1_1cosh__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20float_20_3e',['cosh_func&lt; float &gt;',['../db/d8d/structcv_1_1cudev_1_1cosh__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20schar_20_3e',['cosh_func&lt; schar &gt;',['../df/dd8/structcv_1_1cudev_1_1cosh__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20short_20_3e',['cosh_func&lt; short &gt;',['../dc/d8a/structcv_1_1cudev_1_1cosh__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20uchar_20_3e',['cosh_func&lt; uchar &gt;',['../de/d73/structcv_1_1cudev_1_1cosh__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20uint_20_3e',['cosh_func&lt; uint &gt;',['../d5/ddd/structcv_1_1cudev_1_1cosh__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20ushort_20_3e',['cosh_func&lt; ushort &gt;',['../d2/dd3/structcv_1_1cudev_1_1cosh__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['countnonzeroexprbody',['CountNonZeroExprBody',['../dd/d49/structcv_1_1cudev_1_1CountNonZeroExprBody.html',1,'cv::cudev']]],
  ['creatornotfound',['CreatorNotFound',['../db/d35/classcvflann_1_1CreatorNotFound.html',1,'cvflann']]],
  ['ct_5fassert_5ffailure',['CT_ASSERT_FAILURE',['../da/d73/structNcvCTprep_1_1CT__ASSERT__FAILURE.html',1,'NcvCTprep']]],
  ['ct_5fassert_5ffailure_3c_20true_20_3e',['CT_ASSERT_FAILURE&lt; true &gt;',['../dc/dcf/structNcvCTprep_1_1CT__ASSERT__FAILURE_3_01true_01_4.html',1,'NcvCTprep']]],
  ['cubicinterptr',['CubicInterPtr',['../d3/def/structcv_1_1cudev_1_1CubicInterPtr.html',1,'cv::cudev']]],
  ['cubicinterptrsz',['CubicInterPtrSz',['../d2/d00/structcv_1_1cudev_1_1CubicInterPtrSz.html',1,'cv::cudev']]],
  ['cv32suf',['Cv32suf',['../d9/df3/unionCv32suf.html',1,'']]],
  ['cv64suf',['Cv64suf',['../de/d55/unionCv64suf.html',1,'']]],
  ['cvabstractcamera',['CvAbstractCamera',['../d0/de8/interfaceCvAbstractCamera.html',1,'']]],
  ['cvattrlist',['CvAttrList',['../df/dea/structCvAttrList.html',1,'']]],
  ['cvavgcomp',['CvAvgComp',['../d5/d8a/structCvAvgComp.html',1,'']]],
  ['cvbox2d',['CvBox2D',['../da/d13/structCvBox2D.html',1,'']]],
  ['cvchain',['CvChain',['../d9/d08/structCvChain.html',1,'']]],
  ['cvchainptreader',['CvChainPtReader',['../d9/db9/structCvChainPtReader.html',1,'']]],
  ['cvconnectedcomp',['CvConnectedComp',['../d3/df6/structCvConnectedComp.html',1,'']]],
  ['cvcontour',['CvContour',['../dd/deb/structCvContour.html',1,'']]],
  ['cvconvexitydefect',['CvConvexityDefect',['../d7/dec/structCvConvexityDefect.html',1,'']]],
  ['cvfilenode',['CvFileNode',['../dc/d73/structCvFileNode.html',1,'']]],
  ['cvfont',['CvFont',['../db/d2b/structCvFont.html',1,'']]],
  ['cvgraph',['CvGraph',['../db/da6/structCvGraph.html',1,'']]],
  ['cvgraphedge',['CvGraphEdge',['../d0/db1/structCvGraphEdge.html',1,'']]],
  ['cvgraphscanner',['CvGraphScanner',['../d6/d89/structCvGraphScanner.html',1,'']]],
  ['cvgraphvtx',['CvGraphVtx',['../d3/d89/structCvGraphVtx.html',1,'']]],
  ['cvgraphvtx2d',['CvGraphVtx2D',['../df/d9e/structCvGraphVtx2D.html',1,'']]],
  ['cvhaarclassifier',['CvHaarClassifier',['../d5/de9/structCvHaarClassifier.html',1,'']]],
  ['cvhaarclassifiercascade',['CvHaarClassifierCascade',['../d6/d3d/structCvHaarClassifierCascade.html',1,'']]],
  ['cvhaarfeature',['CvHaarFeature',['../d7/d82/structCvHaarFeature.html',1,'']]],
  ['cvhaarstageclassifier',['CvHaarStageClassifier',['../db/df3/structCvHaarStageClassifier.html',1,'']]],
  ['cvhistogram',['CvHistogram',['../df/df3/structCvHistogram.html',1,'']]],
  ['cvhumoments',['CvHuMoments',['../dd/d46/structCvHuMoments.html',1,'']]],
  ['cvkalman',['CvKalman',['../d5/de6/structCvKalman.html',1,'']]],
  ['cvlevmarq',['CvLevMarq',['../d2/d70/classCvLevMarq.html',1,'']]],
  ['cvlineiterator',['CvLineIterator',['../d9/d22/structCvLineIterator.html',1,'']]],
  ['cvmat',['CvMat',['../d3/db2/structCvMat.html',1,'']]],
  ['cvmatnd',['CvMatND',['../d4/d4c/structCvMatND.html',1,'']]],
  ['cvmemblock',['CvMemBlock',['../dd/d24/structCvMemBlock.html',1,'']]],
  ['cvmemstorage',['CvMemStorage',['../db/d76/structCvMemStorage.html',1,'']]],
  ['cvmemstoragepos',['CvMemStoragePos',['../da/d36/structCvMemStoragePos.html',1,'']]],
  ['cvmoduleinfo',['CvModuleInfo',['../df/db0/structCvModuleInfo.html',1,'']]],
  ['cvmoments',['CvMoments',['../d6/dc6/structCvMoments.html',1,'']]],
  ['cvnarrayiterator',['CvNArrayIterator',['../d3/da5/structCvNArrayIterator.html',1,'']]],
  ['cvphotocamera',['CvPhotoCamera',['../d4/d1d/interfaceCvPhotoCamera.html',1,'']]],
  ['cvphotocameradelegate_2dp',['CvPhotoCameraDelegate-p',['../d9/d97/protocolCvPhotoCameraDelegate-p.html',1,'']]],
  ['cvpluginfuncinfo',['CvPluginFuncInfo',['../df/d6a/structCvPluginFuncInfo.html',1,'']]],
  ['cvpoint',['CvPoint',['../dc/dd1/structCvPoint.html',1,'']]],
  ['cvpoint2d32f',['CvPoint2D32f',['../da/db6/structCvPoint2D32f.html',1,'']]],
  ['cvpoint2d64f',['CvPoint2D64f',['../df/d5d/structCvPoint2D64f.html',1,'']]],
  ['cvpoint3d32f',['CvPoint3D32f',['../d7/db2/structCvPoint3D32f.html',1,'']]],
  ['cvpoint3d64f',['CvPoint3D64f',['../d4/da0/structCvPoint3D64f.html',1,'']]],
  ['cvrect',['CvRect',['../d0/d76/structCvRect.html',1,'']]],
  ['cvscalar',['CvScalar',['../d6/db3/structCvScalar.html',1,'']]],
  ['cvseq',['CvSeq',['../d6/dde/structCvSeq.html',1,'']]],
  ['cvseqblock',['CvSeqBlock',['../dd/de2/structCvSeqBlock.html',1,'']]],
  ['cvseqreader',['CvSeqReader',['../d8/de9/structCvSeqReader.html',1,'']]],
  ['cvseqwriter',['CvSeqWriter',['../d6/d41/structCvSeqWriter.html',1,'']]],
  ['cvset',['CvSet',['../d8/dad/structCvSet.html',1,'']]],
  ['cvsetelem',['CvSetElem',['../d0/df0/structCvSetElem.html',1,'']]],
  ['cvsize',['CvSize',['../da/dcb/structCvSize.html',1,'']]],
  ['cvsize2d32f',['CvSize2D32f',['../dd/d16/structCvSize2D32f.html',1,'']]],
  ['cvslice',['CvSlice',['../d5/d3e/structCvSlice.html',1,'']]],
  ['cvsparsemat',['CvSparseMat',['../dd/d4b/structCvSparseMat.html',1,'']]],
  ['cvsparsematiterator',['CvSparseMatIterator',['../d8/d39/structCvSparseMatIterator.html',1,'']]],
  ['cvsparsenode',['CvSparseNode',['../df/d7a/structCvSparseNode.html',1,'']]],
  ['cvstereobmstate',['CvStereoBMState',['../dd/d3f/structCvStereoBMState.html',1,'']]],
  ['cvstring',['CvString',['../d7/d16/structCvString.html',1,'']]],
  ['cvstringhashnode',['CvStringHashNode',['../da/dbd/structCvStringHashNode.html',1,'']]],
  ['cvtermcriteria',['CvTermCriteria',['../d8/d2b/structCvTermCriteria.html',1,'']]],
  ['cvtreenodeiterator',['CvTreeNodeIterator',['../d7/d14/structCvTreeNodeIterator.html',1,'']]],
  ['cvtype',['CvType',['../d1/def/structcv_1_1flann_1_1CvType.html',1,'cv::flann']]],
  ['cvtype',['CvType',['../d3/dba/structCvType.html',1,'']]],
  ['cvtype_3c_20char_20_3e',['CvType&lt; char &gt;',['../dc/d89/structcv_1_1flann_1_1CvType_3_01char_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20double_20_3e',['CvType&lt; double &gt;',['../dc/d69/structcv_1_1flann_1_1CvType_3_01double_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20float_20_3e',['CvType&lt; float &gt;',['../dc/dd6/structcv_1_1flann_1_1CvType_3_01float_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20short_20_3e',['CvType&lt; short &gt;',['../d2/def/structcv_1_1flann_1_1CvType_3_01short_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20unsigned_20char_20_3e',['CvType&lt; unsigned char &gt;',['../d7/da5/structcv_1_1flann_1_1CvType_3_01unsigned_01char_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20unsigned_20short_20_3e',['CvType&lt; unsigned short &gt;',['../d9/d57/structcv_1_1flann_1_1CvType_3_01unsigned_01short_01_4.html',1,'cv::flann']]],
  ['cvtypeinfo',['CvTypeInfo',['../d7/d7c/structCvTypeInfo.html',1,'']]],
  ['cvvideocamera',['CvVideoCamera',['../db/da9/interfaceCvVideoCamera.html',1,'']]],
  ['cvvideocameradelegate_2dp',['CvVideoCameraDelegate-p',['../db/dbd/protocolCvVideoCameraDelegate-p.html',1,'']]],
  ['cylindricalportraitprojector',['CylindricalPortraitProjector',['../df/d3f/structcv_1_1detail_1_1CylindricalPortraitProjector.html',1,'cv::detail']]],
  ['cylindricalportraitwarper',['CylindricalPortraitWarper',['../dd/d19/classcv_1_1detail_1_1CylindricalPortraitWarper.html',1,'cv::detail']]],
  ['cylindricalprojector',['CylindricalProjector',['../dd/d96/structcv_1_1detail_1_1CylindricalProjector.html',1,'cv::detail']]],
  ['cylindricalwarper',['CylindricalWarper',['../d3/dd6/classcv_1_1detail_1_1CylindricalWarper.html',1,'cv::detail']]],
  ['cylindricalwarper',['CylindricalWarper',['../d7/df6/classcv_1_1CylindricalWarper.html',1,'cv']]],
  ['cylindricalwarpergpu',['CylindricalWarperGpu',['../d9/dbd/classcv_1_1detail_1_1CylindricalWarperGpu.html',1,'cv::detail']]]
];
