var searchData=
[
  ['datamov_5futils_2ehpp',['datamov_utils.hpp',['../df/dcf/datamov__utils_8hpp.html',1,'']]],
  ['deblurring_2ehpp',['deblurring.hpp',['../d4/db5/deblurring_8hpp.html',1,'']]],
  ['defines_2eh',['defines.h',['../d8/db0/defines_8h.html',1,'']]],
  ['defs_2eh',['defs.h',['../d5/d64/defs_8h.html',1,'']]],
  ['deriv_2ehpp',['deriv.hpp',['../df/d27/expr_2deriv_8hpp.html',1,'']]],
  ['deriv_2ehpp',['deriv.hpp',['../dd/da3/ptr2d_2deriv_8hpp.html',1,'']]],
  ['detection_5fbased_5ftracker_2ehpp',['detection_based_tracker.hpp',['../d5/d5a/detection__based__tracker_8hpp.html',1,'']]],
  ['detection_5fof_5fplanar_5fobjects_2emarkdown',['detection_of_planar_objects.markdown',['../dd/d5c/detection__of__planar__objects_8markdown.html',1,'']]],
  ['dev_5fwith_5focv_5fon_5fandroid_2emarkdown',['dev_with_OCV_on_Android.markdown',['../d9/d37/dev__with__OCV__on__Android_8markdown.html',1,'']]],
  ['directx_2ehpp',['directx.hpp',['../df/d8b/directx_8hpp.html',1,'']]],
  ['discrete_5ffourier_5ftransform_2emarkdown',['discrete_fourier_transform.markdown',['../d7/d0e/discrete__fourier__transform_8markdown.html',1,'']]],
  ['display_5fimage_2emarkdown',['display_image.markdown',['../dd/d8a/display__image_8markdown.html',1,'']]],
  ['dist_2eh',['dist.h',['../d1/d82/dist_8h.html',1,'']]],
  ['distance_5ftransform_2emarkdown',['distance_transform.markdown',['../dc/d15/distance__transform_8markdown.html',1,'']]],
  ['documentation_5ftutorial_2emarkdown',['documentation_tutorial.markdown',['../d6/d6b/documentation__tutorial_8markdown.html',1,'']]],
  ['dummy_2eh',['dummy.h',['../d2/d94/dummy_8h.html',1,'']]],
  ['dynamic_5fbitset_2eh',['dynamic_bitset.h',['../da/d5c/dynamic__bitset_8h.html',1,'']]],
  ['dynamic_5fsmem_2ehpp',['dynamic_smem.hpp',['../d8/d9c/core_2include_2opencv2_2core_2cuda_2dynamic__smem_8hpp.html',1,'']]],
  ['dynamic_5fsmem_2ehpp',['dynamic_smem.hpp',['../d6/d7d/cudev_2include_2opencv2_2cudev_2block_2dynamic__smem_8hpp.html',1,'']]]
];
